# Generated by Django 5.0.6 on 2024-06-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_remove_coffee_image_coffee_is_available_coffee_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
