# Generated by Django 5.0.6 on 2024-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_coffee_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='stock',
        ),
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_images/'),
        ),
        migrations.DeleteModel(
            name='CoffeeImageModel',
        ),
    ]
