# Generated by Django 5.0.6 on 2024-06-27 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_remove_coffee_is_available_remove_coffee_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='image',
        ),
        migrations.AddField(
            model_name='coffee',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CoffeeImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coffee_images/')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coffee.coffee')),
            ],
        ),
    ]
